language: cpp
dist: xenial
os: linux
compiler: gcc

cache:
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: lcov

install:
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

script: ./build.sh

after_success:
- lcov --directory . --capture --output-file coverage.info'
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
- lcov --list coverage.info
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"